name: vk_video
description: "The vk_video package facilitates VK video playback integration in Flutter apps, supporting the VK Video API for seamless embedding and control."
version: 1.0.3
repository: https://github.com/ultra-rony/vk_video
homepage: https://rony.fun

topics: [vk, vk-video, player, video]

environment:
  sdk: ^3.0.0
  flutter: 3.24.4

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
dependency_overrides:
# sdk: 3.24.4
screenshots:
  - description: The logo of the vk_video package.
    path: screenshots/logo.png
